update wp_postmeta set meta_value = concat('page-templates/',meta_value) where meta_key = 'custom_post_template';
update wp_postmeta set meta_value = concat('page-templates/',meta_value) where meta_key = '_wp_page_template';

select distinct meta_value from wp_postmeta where meta_value in ('page-templates/acf-company.php',
'page-templates/acf-home.php',
'page-templates/acf-livechathome.php',
'page-templates/customerstory.php',
'page-templates/landing-chatbot-demo.php',
'page-templates/landing-no-menu-simple-footer.php',
'page-templates/landing-no-menu.php',
'page-templates/page-company.php',
'page-templates/page-forum.php',
'page-templates/page-helpdesk.php',
'page-templates/page-home.php',
'page-templates/page-knowledgebase.php',
'page-templates/page-livechat-home.php',
'page-templates/page-livechat-nomenu.php',
'page-templates/page-livechat-nomenunofooter.php',
'page-templates/page-livechat.php',
'page-templates/page-noheaderandfooter.php',
'page-templates/page-ticket.php',
'page-templates/page-websitemonitor.php',
'page-templates/platformAI.php',
'page-templates/platformAIClickThrough.php',
'page-templates/platformLiveChat.php',
'page-templates/platformLiveChatClickThrough.php',
'page-templates/platformMultichannel.php',
'page-templates/platformMultichannelClickThrough.php',
'page-templates/platformOthers.php',
'page-templates/resource page template.php',
'page-templates/resources.php',
'page-templates/single-blog.php',
'page-templates/singlenosidebar.php',
'page-templates/solutionIndustriesClickThrough.php',
'page-templates/solutionIndustriesLanding.php',
'page-templates/solutionUseCaseClickThrough.php',
'page-templates/solutionUseCaseLanding.php') group by meta_value
